apiVersion: v1
kind: Namespace
metadata:
  name: hunyuan3d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hunyuan3d-hf-cache-pvc
  namespace: hunyuan3d
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunyuan3d
  namespace: hunyuan3d
  labels:
    app: hunyuan3d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hunyuan3d
  template:
    metadata:
      labels:
        app: hunyuan3d
    spec:
      runtimeClassName: nvidia
      containers:
      - name: hunyuan3d
        image: registry.example.invalid:5000/hunyuan3d:2.1-shape-1
        imagePullPolicy: Always
        ports:
        - containerPort: 7860
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          periodSeconds: 10
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 32Gi
            ephemeral-storage: 2Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 16Gi
            ephemeral-storage: 512Mi
        volumeMounts:
        - mountPath: /data
          name: hf-cache
      volumes:
      - name: hf-cache
        persistentVolumeClaim:
          claimName: hunyuan3d-hf-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hunyuan3d-service
  namespace: hunyuan3d
spec:
  type: NodePort
  selector:
    app: hunyuan3d
  ports:
    - port: 7860
      targetPort: 7860
      nodePort: 30860
